### ISSUE TITLE
Task1-2简单图论.md勘误

### ISSUE THREAD

**Issue by ifwind** [datawhalechina/team-learning-nlp#4]
1、定理六可以表述更加清晰：
![image](https://user-images.githubusercontent.com/46741827/121832538-e0c89a00-ccfc-11eb-87b4-879882bbf87a.png)
个人感觉可以补充表述一下更加清晰：在无权图中，若$\mathbf{A}^{n}[i,j]=1$表示从结点$v_i$到结点$v_j$有一条长度为n的可通行路径。（参考：https://blog.csdn.net/qq_40008198/article/details/103541485）
![image](https://user-images.githubusercontent.com/46741827/121832707-44eb5e00-ccfd-11eb-96cd-928e7d6cdbf9.png)

2、定义十二关于图直径表述有误：图直径应为图中所有结点对之间的最短路径的最**大**值。
![image](https://user-images.githubusercontent.com/46741827/121831755-d86f5f80-ccfa-11eb-9bb3-ebd22c7f2e24.png)
修改后文件：
[2-简单图论.md](https://github.com/datawhalechina/team-learning-nlp/files/6645291/2-.md)

**Comment by RongqinChen** [comment]
感谢指出错误，修正版马上提交。另外提醒一下，$\mathbf{A}^{n}[i,j]$ 不一定等于1，它等于“行走”的数量。
